package com.tripleaxe.monitor.mapper;

import com.tripleaxe.monitor.model.RequestDetail;
import com.tripleaxe.monitor.model.RequestDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RequestDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_detail
     *
     * @mbg.generated
     */
    long countByExample(RequestDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_detail
     *
     * @mbg.generated
     */
    int deleteByExample(RequestDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_detail
     *
     * @mbg.generated
     */
    int insert(RequestDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_detail
     *
     * @mbg.generated
     */
    int insertSelective(RequestDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_detail
     *
     * @mbg.generated
     */
    List<RequestDetail> selectByExample(RequestDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_detail
     *
     * @mbg.generated
     */
    RequestDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_detail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RequestDetail record, @Param("example") RequestDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_detail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RequestDetail record, @Param("example") RequestDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RequestDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RequestDetail record);
}